import { siteName } from "../siteName.js";
import type { Component } from "../types/Component.js";
import { E } from "./E.js";

type Props = {
  title: string;
};

export const Layout: Component<Props> = ({ title }, ...children) => {
  return E(
    "html",
    { lang: "ja" },
    E(
      "head",
      {},
      E("meta", { name: "viewport", content: "width=device-width" }),
      E("meta", { charset: "utf-8" }),
      E("meta", { name: "theme-color", content: "#4c485b" }),
      E("title", {}, title),
      // style.css is generated by src/export.ts
      E("link", { rel: "preload", href: "/style.css", as: "style" }),
      E("link", { rel: "stylesheet", href: "/style.css" }),
      // https://realfavicongenerator.net/
      E("link", {
        rel: "apple-touch-icon",
        sizes: "180x180",
        href: "/apple-touch-icon.png",
      }),
      E("link", {
        rel: "icon",
        type: "image/png",
        sizes: "32x32",
        href: "/favicon-32x32.png",
      }),
      E("link", {
        rel: "icon",
        type: "image/png",
        sizes: "16x16",
        href: "/favicon-16x16.png",
      }),
      E("link", {
        rel: "manifest",
        href: "/site.webmanifest",
      }),
      E("link", {
        rel: "mask-icon",
        href: "/safari-pinned-tab.svg",
        color: "#5bbad5",
      }),
      E("meta", {
        name: "msapplication-TileColor",
        content: "#603cba",
      })
    ),
    E(
      "header",
      { class: "p-4 max-w-screen-md mx-auto" },
      E(
        "a",
        {
          href: "/",
          class: "text-xl text-white font-bold underline-none no-underline",
        },
        siteName
      )
    ),
    E("body", {}, ...children),
    E("footer", { class: "text-xs text-center my-4" }, "© 2022 dqn")
  );
};
